#!/bin/bash

flags="-S -ast -sym"

output_dir="output"

compile="java -cp mjc.jar mjc.JVMMain $flags" 

inheritence_tests=0 # Set to 1 to test inheritence

compile_tests="student-test-cases/compile/*/*.java"
noncomplile_tests="student-test-cases/noncomplie/*/*.java minijava_tests/no_inheritence/err_*.java"
execute_tests="student-test-cases/execute/*/*.java minijava_tests/no_inheritence/ok*.java"
nonexecute_tests="student-test-cases/nonexecute/*/*.java"

if [ $inheritence_tests -eq 1 ]; then
	execute_tests="$execute_tests minijava_tests/inheritence/*.java"
fi

##Filename to dir
function mkdirname() {
	echo "$1" | sed 's/\.java//g' | tr '[A-Z]' '[a-z]'
}

function build_mjc() {
	echo -ne "Compiling compiler \t"
	res=$(ant)
	if [ $? -eq 0 ]; then
		echo "OK"
		return 0
	else
		echo "ERROR"
		echo -e  "$res"
		return 1
	fi
}

## Functions
function compile() {
	_dirname=$(mkdirname $1)
	mkdir -p "$_dirname"
	eval $compile -o "$output_dir/$_dirname" $1 2>&1
}

function extention_list() {
	_lines=$(cat DESC | wc -l)
	tail -n $(($_lines-2)) DESC
}

function test_extentions() {
	_file="$1"
	_extentions=$(cat $_file | grep "//.*EXT" | sed -e 's/\/\/EXT:\(.*\)/\1/')
	for ext in $_extentions; do
		count=$(echo $extentions | grep $ext -cx)
		if [[ $count == "0" ]]; then
			return 1
		fi
	done
	return 0
}

# Expect compilation of $1 to succed
function compile_ok() {
	_file=$1
	echo -ne "Compiling: $_file \t\t"
	test_extentions $_file
	if [ $? -eq 0 ]; then
		_res=$(compile $_file)
		ex=$?
		if [ $ex -eq 0 ]; then
			echo "OK"
			return 0
		else
			echo "ERROR"
			echo "Compiler output: return status $ex"
			echo -e "$_res\n"
			return 1
		fi
	else
		echo "EXT MISS"
		return 0
	fi
}

#Expect compilation of $1 to fail
function compile_fail() {
	_file=$1
	echo -ne "Compiling: $_file \t\t"
	test_extentions $_file
	if [ $? -eq 0 ]; then
		_res=$(compile $_file)
		ex=$?
		if [ $ex -ne 0 ]; then
			echo "OK"
			return 0
		else
			echo "ERROR"
			return 1
		fi
	else
		echo "EXT MISS"
		return 0
	fi
}

## BEGIN EXECUTION

extentions=$(extention_list)

# Set no_exec to 1 in shell to be able to source this file without shit executing!
if [[ $no_exec != "1" ]]; then

build_mjc

if [ $? -ne 0 ]; then
	exit 1
fi

rm -rf $output_dir
mkdir $output_dir

any_error=0

# Start by compiling everything that should be compiled
echo "Compling code"
for file in $(ls $compile_tests $execute_tests $nonexecute_tests); do
	compile_ok $file
	if [ $? -ne 0 ]; then
		any_error=1
	fi
done

if [ $any_error -eq 0 ]; then
	echo "Compiling code that should fail"

	for file in $(ls $noncomplile_tests); do
		compile_fail $file
		if [ $? -ne 0 ]; then
			any_error=1
		fi
	done
	#echo "Assembling code"
fi

fi
